### ISSUE TITLE
Add automake test for C99 standards compliance

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#102]
**Is your feature request related to a problem? Please describe.**
A recent gcc version is required, even if non-GNU compilers, in order to support modern C99 C syntax.

**Describe the solution you'd like**
A automake `configure` check to warn users that their compiler isn't supported. (Otherwise, the first indication of a problem will be a compiler error on the new C99 syntax)

Until then, documentation describing this requirement should be added to README.md

**Describe alternatives you've considered**

**Additional context**

**Comment by underwoo** [comment]
The test that is needed in `configure.ac` is:

```
AC_C__GENERIC
```

This should be added after the C compiler is found in `configure.ac`.

__Note__: I'm adding this here to help find the test later.
