### ISSUE TITLE
Need more complete  build instructions for RDHPCS  sites.

### ISSUE THREAD

**Issue by ngs333** [NOAA-GFDL/FRE-NCtools#116]
Some users at RDHCPS sites have had build problems do to the environment . The current installation instructions
need to be updated and particularly is should be noted that the environment should be clean.  An email from Seth Underwood explains:

" After some looking around, and trying to reproduce the build problem on hera, I remember what the issue is and how to fix it.  The last time we saw this issue, it was on orion and was tied to lmod's refusal to allow a user to have two compiler modules loaded.  To get around that lmod limitation, and to mimic what we do at GFDL and gaea to ensure we use the same build environment, I added site configurations for nescc and orion in the repository.  However, I now see we did not update the install instructions to indicate how to use it.

In the repository, are files for different RDHPCS sites:
site-configs/gfdl
site-configs/gfdl-ws
site-configs/ncrc
site-configs/nescc
site-configs/orion

In each site directory is an `env.sh` script and a `config.site`.  The `env.sh` script will write out to stdout the commands the user will need to run to configure their environment.  The user will then need to run those commands in their shell.  This can be accomplished by passing the output to `eval`:

eval `/path/to/site-configs/<site>/env.sh`

The `env.sh` script does not check what is already in the environment, so doing the above in a clean environment will give the best results.' "

**Comment by underwoo** [comment]
@ngs333 I understand the desire to make FRE-NCtools _as easy to install as possible_, but we need to work to ensure the automake/autoconf build is correct and generic as we can.  Each HPC system (even the RDHPCS systems) is different in how the software stack is configured.  We will do the best we can, but we can only go so far.  The site-configs files are in place to help, but should not be considered supported.  They are not tested frequently enough to ensure they always work.  Users who have difficulty building on their site should reach out to their admin/IT staff for site-specific information beyond `autoconf && configure && make && make install`.
