### ISSUE TITLE
`tools/remap_land/remap_land.c` fails to compile with C99 error

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FRE-NCtools#143]
**Describe the bug**
`tools/remap_land/remap_land.c` fails to compile with 

```
../../../tools/remap_land/remap_land.c:2796:9: error: implicit declaration of function 'time' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```

**To Reproduce**
Build FRE-NCtools with a newer, fully C-99 compliant compiler

**Expected behavior**
FRE-NCtools builds and runs.

**System Environment**
Describe the system environment, include:
- OS: Mac OS 11.6.4
- Compiler(s): Apple clang version 13.0.0 (clang-1300.0.29.30)

**Additional Information**

Adding `#include <time.h>` to `remap_land.c` does allow the compilation to succeed, but I do not know if this is the desired way to fix this in remap_land.

**Comment by ngs333** [comment]
@underwoo 
Looks like I missed the implicit declaration warning on when I was working on this.
What you have should work.  Note srand() expects an unsinged int as argument , so if the time_t  returned from time() is something that cannot fit in an unsinged int, what may be safer is:
```
 time_t ltime = time(NULL);
  unsigned int itime = ltime & UINT_MAX;
  srand(itime);
```
-
