### ISSUE TITLE
Add an option to not build/install the ocean_model_grid_generator?

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FRE-NCtools#144]
The addition of the ocean_model_grid_generator (omgg) has increased the complexity of installing FRE-NCtools.  While it is understandable omgg is included as part of FRE-NCtools, omgg  is a pure python script and does not interact with the other FRE-NCtools applications.  LIkewise, other FRE-NCtools do not require omgg to operate.  

omgg is included in FRE-NCtools as a separate package and can be installed with autoconf/automake or pip.  

Should we include a configure option (--disable-omgg|--without-omgg) to not configure/build/install omgg?

**Comment by ngs333** [comment]
@underwoo , @ceblanton 
I think its a good idea. Perhaps it can be discussed at the workflow Thusrday meeting?
