### ISSUE TITLE
Improve affinity.c conditional compilation and remove duplicate.

### ISSUE THREAD

**Issue by ngs333** [NOAA-GFDL/FRE-NCtools#17]
There are two versions of the affinity.c functions:
/tools/simple_hydrog/lakes/affinity.c
/tools/libfrencutils/affinity.c
They actually try to do the same thing so one of them should be removed.  One should consider putting them in 
a utility directory, and also having it be as similar as possible to that in libFMS.

Additionally, they are conditionally compiled depending on available OS libraries.
The flag HAVE_GETTID is used to control the compilation. This flag is being picked up (through a # include statement in the .c files) from the autotools generated config.h file. It is preferable that instead autotools have the CFLAGS and FCFLAGS
determine  a -D HAVE_GETTID compile option flag and add that to the the CFLAGS and FCFLAGS.

**Comment by underwoo** [comment]
@ngs333, with the merge of #22, there is only one version of `affinity.c`.  However, we should use the version that is included in [NOAA-GFDL/FMS](https://github.com/NOAA-GFDL/FMS/blob/master/affinity/affinity.c).  When taken, some updates to `configure.ac` will need to be made to test for items.  Look at the [`configure.ac`](https://github.com/NOAA-GFDL/FMS/blob/master/configure.ac) in the NOAA-GFDL/FMS repository
