### ISSUE TITLE
make_hgrid bad call to get_grid_great_circle_area

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FRE-NCtools#20]
**Describe the bug**
The source `make_hgrid/create_lonlat_grid.c` uses an implicit declaration to a library function `get_grid_great_circle_area` which is in the `libfrencutils.a` library.  Compilers when checking for c99 standards will throw a warning.  As far as I can tell, the only location `get_grid_great_circle_area` is only defined in `libfrenctools/create_xgrid.c` with the following interface:

```
void get_grid_great_circle_area(const int *nlon, const int *nlat, const double *lon, const double *lat, double *area);
```

`create_lonlat_grid.c` calls `get_grid_great_circle_area` in two locations with the following calls:

```
get_grid_great_circle_area(&nx, &ny, x_rad, y_rad, area);
get_grid_great_circle_area(&nx, &ny, cart_x, cart_y, cart_z, area);
```

The second call to `get_great_circle_area` has an extra passed in parameter `cart_z`.  I'm not sure what compilers do in this case, use `cart_z` as the `area` within `get_grid_great_circle_area`, or something else.

**To Reproduce**
Compile make_hgrid with c99 standard checking to get the warning.  Nothing else to reproduce.

**Expected behavior**
No warnings with c99 standard checking.  The `get_grid_great_circle_area` is defined via a `#include <create_xgrid.h>`, which would have caught this error, and not allowed the compile to complete.

**System Environment**
All systems.  Error in the code

**Comment by underwoo** [comment]
PR #26 has, what I believe to be the correction for this.

**Comment by ngs333** [comment]
PR #26 did correct issue.
