### ISSUE TITLE
Attempting to regrid vectors with `fregrid` raises an error

### ISSUE THREAD

**Issue by spencerkclark** [NOAA-GFDL/FRE-NCtools#211]
**Describe the bug**

Disclaimer: apologies, this may be a long-known problem, but I was not able to find an existing issue in the repository.  No matter what though I would be interested to learn more about the history and status of this option.  Thanks in advance for your help!

`fregrid` [advertises an ability](https://data1.gfdl.noaa.gov/~arl/pubrel/r/mom4p1/src/mom4p1/doc/mosaic_tool.html#fregrid) for regridding the horizontal components of a spherical vector field through its `--u_field` and `--v_field` options.  This is useful since regridding a spherical vector field by independently regridding its components is not necessarily accurate, particularly near the poles, since the spherical unit vectors change their direction depending on position.  One way to approach this is to transform the spherical vector field to a Cartesian vector field (whose unit vectors are translationally invariant) then do the regridding, and then transform back to a spherical vector field.

When provided a `--u_field` and `--v_field`, however, `fregrid` raises a seemingly unrelated error:
```
$ fregrid --input_mosaic /lustre/f2/dev/Spencer.Clark/2023-02-21-GRIDS/C96/C96_mosaic.nc --nlat 180 --nlon 360 --input_file example --output_file example_1_deg.nc --u_field UGRD500 --v_field VGRD500 --interp_method bilinear --latBegin -89.5 --latEnd 89.5
****fregrid: first order conservative scheme will be used for regridding.
Error from pe 0: fregrid: currently does not support vertical interpolation, contact developer
```

If I comment out [the line where this error is raised](https://github.com/NOAA-GFDL/FRE-NCtools/blob/83acb799f47dfa27b433a131e9f7c1310767cc59/tools/fregrid/fregrid.c#L859), I can get `fregrid` to run in vector mode; however, it only produces reasonable looking results when using bilinear interpolation.  The figure below shows some snapshots of the zonal wind at 500 hPa regridded with a number of methods (varying `--interp_method` by column, and varying scalar vs. vector mode by row).

![2023-03-10-UGRD500-snapshots](https://user-images.githubusercontent.com/6628425/224755350-ccb0ca3c-8145-4ce7-b9b6-e9a1c7767c60.png)

In my reading of [the code-path in the bilinear case](https://github.com/NOAA-GFDL/FRE-NCtools/blob/83acb799f47dfa27b433a131e9f7c1310767cc59/tools/fregrid/bilinear_interp.c#L476-L559) it indeed seems like `fregrid` is taking the transform to Cartesian, regrid, and transform back to spherical approach.  I have not looked carefully at the other `conserve_order1` or `conserve_order2` code paths, however.

My question is perhaps two-fold:
1. Is the error currently raised on the basis that the conservative regridding methods produce incorrect results in vector mode?  Could this be relaxed such that this option was at least exposed for the `bilinear` regridding method?  Or maybe there is another subtle bug I am not aware of?
2. Am I correct in my understanding that the intent of this vector regridding option is for regridding 2D conventional spherical vector fields, and that the approach it takes is converting to a Cartesian vector field, regridding, and converting back to a conventional spherical vector field?

A workaround would be to convert the spherical vector field to Cartesian outside of `fregrid`, then use `fregrid` to do the regridding, and finally convert back to spherical outside of `fregrid`.

**To Reproduce**

On Gaea, to reproduce the error one can use:
```
$ cp /lustre/f2/dev/Spencer.Clark/2023-03-13-fregrid-issue/example.tile*.nc .
$ fregrid --input_mosaic /lustre/f2/dev/Spencer.Clark/2023-02-21-GRIDS/C96/C96_mosaic.nc --nlat 180 --nlon 360 --input_file example --output_file example_1_deg.nc --u_field UGRD500 --v_field VGRD500 --interp_method bilinear --latBegin -89.5 --latEnd 89.5
$ Error from pe 0: fregrid: currently does not support vertical interpolation, contact developer
```

**Expected behavior**

Ideally I would expect no error to be raised and reasonable looking results for all `--interp_method` options.

**System Environment**

Describe the system environment, include:
- OS: SUSE Linux Enterprise Server 15 SP1
- Compiler(s): Intel 19.0.5.281
- netCDF Version: cray-netcdf 4.6.3.2
- Configure options: n/a

cc: @oliverwm1

**Comment by ngs333** [comment]
@spencerkclark , @ceblanton 
Thank you for raising this issue. There are various aspects of this that should be investigated, some that may receive some code improvements in the near term, and some others that we will probably not be able to addressed for a long time.  

First as far as short term changes to the software, I think the messages and/or documentation produced by fregrid can be improved.  

We may consider allowing fregrid to regrid vector variables if the interpolation method is bi-linear.  I expect that to get the go-ahead for such a change we will need to do some work. First since the "scalar modes" have been used at the GFDL for a long time, I'd like to investigate under what conditions those modes produce acceptable answers and under what conditions they don't.   Related to that, we may need some information or analysis for the  output/answer differences between the direct vector with bi-linear interpolation vs n-scalars with bi-linear interpolation for your own case. Certainly the you have two plots on the LHS above at https://github.com/NOAA-GFDL/FRE-NCtools/issues/211#issue-1621835933 look very similar, but numerically which is providing the best answer for you?

Ad far as having a properly working version of "vector mode" conserve order 1 (or 2), I guess that we will not be able to add such a capability in the near term.

**Comment by spencerkclark** [comment]
Thanks @ngs333!

To add a few details after our offline conversation, differences are strongly concentrated in the polar regions.  The plot below shows the zonal and time root mean square difference between the results using vector and scalar mode in the bilinear case for some data for the month of December (the zonal wind at 500 hPa on the left and the meridional wind at 500 hPa on the right).

![2023-03-10-bilinear-rms-difference-zonal-time](https://user-images.githubusercontent.com/6628425/225425758-427ad579-a905-41c1-bda3-06358ec9ecf4.png)

If we zoom in to the North Pole we see zonal and time root mean square differences between the vector and scalar modes of up to 3 m/s, that rapidly decline to a few tenths of a m/s or lower by about 85N.

![2023-03-10-bilinear-rms-difference-zonal-time-north-pole](https://user-images.githubusercontent.com/6628425/225425790-4bc216a9-3232-48b2-8072-fa898639c8af.png)

Maps of the difference for a regridded snapshot of the winds with a linear color scale can be found below:

![2023-03-10-bilinear-snapshots-north-pole-difference](https://user-images.githubusercontent.com/6628425/225425832-e04db1d3-6571-42e2-9cff-baa632ef9232.png)

and the absolute value of the difference for the same snapshot plotted with a logarithmic color scale can be found here:

![2023-03-10-bilinear-snapshots-north-pole-difference-logarithmic](https://user-images.githubusercontent.com/6628425/225426017-83f43b40-d8b7-4c16-9ec2-65c96b4d472b.png)
