### ISSUE TITLE
deprecate `reproduce_siena` option

### ISSUE THREAD

**Issue by rem1776** [NOAA-GFDL/FRE-NCtools#232]
**Describe the bug**
In mosaic_util.c theres a `reproduce_siena` flag that is left over from an incorrect version of the code.

It enables a different algorithm for area calculations in mosaic_util.c and can be enabled as an argument for make_quick_mosaic.

**System Environment**
any

**Additional context**
We should remove/deprecate this if possible since this is planned for deprecation in FMS.

**Comment by ngs333** [comment]
@nikizadehgfdl @ceblanton @rem1776 
Niki and Chris, do you agree we should get rid of the reproduce_siena option?
