### ISSUE TITLE
Licensing needs to be implemented throughout the project

### ISSUE THREAD

**Issue by bensonr** [NOAA-GFDL/FRE-NCtools#24]
**Is your feature request related to a problem? Please describe.**
The licensing is haphazard and inconsistent.  Additionally, we don't have the needed overarching LICENSE.md.

**Describe the solution you'd like**
All files contain a license header referencing LGPL, in the same manner as FMS, with reference to the project.

**Describe alternatives you've considered**
N/A

**Additional context**
This is needed for consistency other NOAA-GFDL projects.

**Comment by ngs333** [comment]
I propose this below for the license text:
```c
!***********************************************************************
!*                   GNU Lesser General Public License
!*
!* This file is part of the GFDL FRE-NCTools system.
!*
!* FRE-NCTools is free software: you can redistribute it and/or modify it under
!* the terms of the GNU Lesser General Public License as published by
!* the Free Software Foundation, either version 3 of the License, or (at
!* your option) any later version.
!*
!* FRE-NCTools is distributed in the hope that it will be useful, but WITHOUT
!* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
!* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
!* for more details.
!*
!* You should have received a copy of the GNU Lesser General Public
!* License along with FRE-NCTools.  If not, see <http://www.gnu.org/licenses/>.
!***********************************************************************
```

Additionally, I believe besides having it at the front of .h, .F90, .c and .inc library and application files, I should also be 
on the same for test applications and well as autotools input files and any scripts.

Does it belong on readme files and instructions?

**Comment by ceblanton** [comment]
Thanks @ngs333 looks good to me. Maybe explicitly refer to the `LICENSE.md` file also? as in

```
!* You should have received a copy of the GNU Lesser General Public
!* License along with FRE-NCTools (LICENSE.md).  If not, see <http://www.gnu.org/licenses/>.
```

I don't think readmes and instructions need the license, but I'm not sure either

**Comment by underwoo** [comment]
While the normal position is that all files in a project should have the
license header, placing it in files that users generally read as-is, e.g.
README.md, Change Logs, contributing, installation instructions, etc,
usually don't have the license header text.  I think for our purposes,
anything that will be parsed/compiled will have the license text added as a
comment.  Anything the user will use without parsing or modification will
not have the license text.
--
Seth Underwood

S/W Development Process Lead
Modeling Systems Group
GFDL/NOAA/DOC
201 Forrestal Road
Princeton, NJ 08540-6649

(609) 452-5847 Office
(304) 376-9002 Cell
(609) 987-5063 Fax
Seth.Underwood@noaa.gov

**Comment by ngs333** [comment]
Thanks!

**Comment by ngs333** [comment]
@underwoo , @ceblanton , @bensonr 
I created PR 41 (https://github.com/NOAA-GFDL/FRE-NCtools/pull/41) , but note its asking for input to resolve or decide on some items.
Thanks
MZ

**Comment by ngs333** [comment]
There is a new PR for the work : https://github.com/NOAA-GFDL/FRE-NCtools/pull/43

**Comment by ngs333** [comment]
Future work moved to this issue : https://github.com/NOAA-GFDL/FRE-NCtools/issues/46

**Comment by ngs333** [comment]
PR #43 covers most of this issue. Some work (copyright years) moved to issue #46
