### ISSUE TITLE
fregrid mpp_get_varname error when regridding Netcdf-4 history files

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#277]
**Describe the bug**
When attempting to regrid variables that are in a Netcdf-4 input file, fregrid fails with errors like:

Error from pe 0: mpp_io(mpp_get_varname): error in get varname from file 09460101.atmos_tracer.tile1.nc: NetCDF: Variable not found

The problem only occurs with Netcdf-4 files and a workaround is setting the deflation and shuffle level manually, e.g. `--deflation=0 --shuffle=0`

**To Reproduce**
Standard fregrid usage:

fregrid --standard_dimension --input_mosaic C192_mosaic.nc --input_file 09460101.atmos_tracer --interp_method conserve_order2 --remap_file .fregrid_remap_file_576_by_360.nc --nlon 576 --nlat 360 --scalar_field bk,pk,ps,sphum,temp,SOA,dust1,dust2,dust3,dust4,dust5,ssalt1,ssalt2,ssalt3,ssalt4,ssalt5,omphil,omphob,bcphil,bcphob,radon,climatology_bounds --output_file out.nc

**Expected behavior**
fregrid should regrid the variables if they are in the file

**System Environment**
Describe the system environment, include:
- OS: [e.g. RHEL 7.2]
- Compiler(s): Type and version [e.g. Intel 19.1]
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by mlee03** [comment]
@ceblanton, great timing!  It works!

**Comment by uramirez8707** [comment]
After merging https://github.com/NOAA-GFDL/FRE-NCtools/pull/278
In order to reproduce the problem, the average_* variables need to be removed. For example:
```
netcdf wut2 {
dimensions:
        time = UNLIMITED ; // (2 currently)
        yh = 320 ;
        xh = 360 ;
        nv = 2 ;
variables:
        float SST(time, yh, xh) ;
                SST:_FillValue = 1.e+20f ;
                SST:missing_value = 1.e+20f ;
                SST:units = "degC" ;
                SST:long_name = "Sea Surface Temperature" ;
                SST:cell_methods = "area:mean yh:mean xh:mean time: mean" ;
                SST:cell_measures = "area: area_t" ;
        double time(time) ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:calendar_type = "JULIAN" ;
                time:calendar = "julian" ;
                time:bounds = "time_bnds" ;
        double time_bnds(time, nv) ;
                time_bnds:units = "days since 0001-01-01 00:00:00" ;
                time_bnds:long_name = "time axis boundaries" ;
        double xh(xh) ;
                xh:units = "degrees_east" ;
                xh:long_name = "h point nominal longitude" ;
                xh:axis = "X" ;
        double yh(yh) ;
                yh:units = "degrees_north" ;
                yh:long_name = "h point nominal latitude" ;
                yh:axis = "Y" ;
```

```
fregrid --standard_dimension --input_mosaic ocean_mosaic.nc --input_file in.nc --interp_method conserve_order1 --nlon 360 --nlat 180 --scalar_field SST --output_file out.nc
```

The problem is here:
https://github.com/NOAA-GFDL/FRE-NCtools/blob/79f5faa513475ae5044ac0d6f999b4616cb7dc6d/tools/libfrencutils/mpp_io.c#L1050-L1054

The code is looping though the variables id in the output file and using the variable id to get the variable name but it us using the input file id! The input file has variable ids [0:4], and the output file has variable ids [0:6] because it has 2 extra variables
```
        double time(time) ;
        double time_bnds(time, bnds) ;
        double lat(lat) ;
        double lat_bnds(lat, bnds) ;
        double lon(lon) ;
        double lon_bnds(lon, bnds) ;
        float SST(time, lat, lon) ;
```
so once it gets to the id of the 5th variable id (lon_bnds), the code will fail because it is not a valid id. 

The solution is to use the fid_out to get the variable name and then check if the variable exists in the input file and if it doesn't leave the loop
```
            mpp_get_varname(fid_out, vid_out, varname);

            // Don't attempt to the get the deflate level if the variable is not in the input file (i.e lat_bnds,
            // lon_bnds)
            if (mpp_var_exist(fid_in, varname) == 0) continue;
```
