### ISSUE TITLE
remap_land needs to work with lm4.1 and lm4.2 data

### ISSUE THREAD

**Issue by ngs333** [NOAA-GFDL/FRE-NCtools#36]
This is an enhancement ticket to upgrade NCTools remap_land application to work with lm4.1 and lm4.2 (CANDIDATE) files in addition to the lm4.0 with which it currently works. It appears that the existing remap_land application makes several assumptions about the fields, their dimensions and indices that are not valid assumptions for the data of lm4.1 and lm4.2. A version working for lm4.1 and lm4.2 is needed by Sergey Malyshev and Meiyun Lin of GFDL.

After analyzing data from lm4.2, it was determined that new dimensions need to be supported:
nspecies (float type)
textlen (float) 
soilCCohort (float)
litterCCohort (float)

The lm4.0 had these combinations of dimensions supported:
[zfull,  tile_index]
[ tile_index]
[cohort_index]
And they had an optional “time” index on the left.

Inspection of lm4.2 data used in the original ticket indicates lm4.2 needs these dimensions additionally:
[soilCCohort,  zfull,  tile_index]
[ literCCohort]

There are numerous int or double (float) variables or fields using the above dimensions.  Additionally, there is one character field in lm4.2 :
species_names (type char; dimensions : nspecies , textlen).

Testing:
Sergey Malyshev has suggested these two tests for identifying inconsistencies between grid spec and the created restart  files:
A) 
  Check if the masks of the generated remapped restart files of glacier/lake/soil/vegetation data match the land mask of the specs of the input destination (dst) grid . To this end I’ve created a comparison program  that compared ```land_mask_tile<i>.nc``` files produced by remap_land  to the corresponding files in dst_grid. Note that some of these files are pre-processed by the “decompress-ncc” utility
[ update 1/25/2021 More specifically, the comparison is the field "mask" of file ```/dst_grid/CXY_grid_tile<i>.nc ``` against  the field "frac" (and independently the field "vegn")  from  file ```/dst_cold_start/land_mask_tile<i>.nc``` and also from file  ```/dst_restart/land_maks_tile<i>.nc.```]

[ Update 1/15/2021 it can be noted that the remap_land app produces a land mask_tile file that is made from both the cold_start land mask file and the  grid tile. For example, see this line
```land_frac_dst[ntile_dst * i + pos] = soil_frac_src[ntile_src * p + l] * soil_frac_cold[i] ``` ]

B) 
 Sergey suggest that the ultimate test is to run the lm4p model  code using as input the dst grid spec and the remapped restart files.  If the spec and the restart files don't match, then the model will issue errors.  Sergeys lm4p model code that is in branch user/slm/dev is used.  The xml to run the model is  a copy of this one:
/ncrc/home1/Sergey.Malyshev/devel/ppa/2020.03/rts.xml.

My copy is located at :
/ncrc/home1/Miguel.Zuniga/remap/sergey/lm4P_xmls/rts.xml

The experiment is a copy of the original experiment “LM4p2c2-SPEAR-ESM4-test”, but it has the gridSpec and initCond specified to use files used by and created by a run of the land_remap app :

```c
<experiment name="LM4p2c2-SPEAR-ESM4-remap
   <description>
      <dataFile label="initCond" target="INPUT/" chksum="" size="" timestamp="">
        <dataSource 
site="ncrc"> /lustre/f2/dev/Miguel.Zuniga/remap/lm4p2c1_SPEAR_18700101.remapped.v20201215.tar </dataSource>
      </dataFile>
      <dataFile label="gridSpec" target="INPUT/" chksum="" size="" timestamp="">
            <dataSource site="ncrc">/lustre/f2/dev/Miguel.Zuniga/remap/mosaic.tar</dataSource>
      </dataFile>
```
Testing status Jan 4 2020:

Test type B) above suggest that there are mismatches.  It indicates that there non-zero points on the remap restart file that are zero on the the grid spec.  In contrast, test type A) above actually suggest that the grid Spec and the remapped file  are in agreement.

The mismatches identified by type B) are all  "R" on the output plots :  i.e. they are present in the
restart but not in the gridSpec. lm4p code has these point values to integer 0; whereas the ```land_mask_tile<i>.nc ``` files has them as a float value greater than 0.  but less than 1.0. (Note, all purely ocean points have the value 0. and purely land points have the value 1.)

Additionally, all the mismatches identified are right on a  ocean/land boundary.

Additionally, the mismatches on  land_mask_tile1.nc are 36 in total – from a total of about 450 land/ocean boundary points. (There are additional mismatches in the other five tiles, also on land/ocean boundary points, qualitatively similar to that of tile 1)

The grid spec is provided in file mosaic.tar. I've been using as the "grid spec" file ```land_mask_tile<i>.nc```. But I've noticed mosaic.tar has additional files

remap_land code location and status:
The new code is on this repo and branch:
https://github.com/ngs333/FRE-NCTools
branch:  remap_land_newdata

The code used on the test was of the last merge before Dec 5. There is an updated version (not yet merged) that is the result of running static analyzers and Intel inspector on the tests.
The updated code is not changing the results of remapped land.

**Comment by ngs333** [comment]
Land maps inconsistency and using the great_circle algorithm ?

Could there be in an inconsistency between NCTools::remap_land and some modes of the FMS
mosaic modules to build a 2D domain. Currently, remap_land used the great_circle_algorithm
when trying to find the nearest neighbor among the destination grid cells (given target cell
in the source grid.  However, FMS mosaic_mod::calc_mosaic_grid_area() gives the option to not use
the great_circle_algorithm when calculating the cell area. The option is determined by
inspecting the grid spec file (grid_spec.nc) and looking to see if a text indicating
great_circle is present. In the current_runs of lm4p with remap_land input restart files and grids,
the grid_specs do not indicate the use of the great_circle_algorithm, and therefore
function calc_mosaic_grid_area() uses the simpler alternative.

Stepping back a little, here is how the differing map_g (the land/sea map based on the grid spec) and
map_r (the lan/sea map based on restart files) functions are build and compared by lm4P code:


A) Building map_g
Initialization of the lm4p model builds a structured grid (SG)  then an unstructured grid
(UG) from the SG. Part of the info placed in th SG is the land fraction of each SG cell:
```c
In land_model_mod::land_model_init
! initialize coordinates
  call get_grid_cell_area    ('LND',lnd%sg_face,lnd%sg_cellarea, domain=lnd%sg_domain)
  call get_grid_comp_area    ('LND',lnd%sg_face,lnd%sg_area,     domain=lnd%sg_domain)
  lnd%sg_landfrac = lnd%sg_area/lnd%sg_cellarea
```
To calculate the landfrac above, this stack is executed:
land_data.F90::lad_data_mod::land_data_init
grid;F90::grid_mod::get_grid_cell_area_SG()
mosaic.F90::mosaic_mod::calc_mosaic_grid_area()
create_xgrid.c::get_grid_area()

As mentioned, calc_mosaic_grid_area() uses the option to not use the great circle algorithm.

Finally, integer map_g(lat_i, lon_j) is set in land_model.F90::check_mask_map like this:
```c
 do it = lnd%ls,lnd%le
     if (lnd%ug_landfrac(it) > 0) &
           map_g(lnd%i_index(it),lnd%j_index(it)) = 1
  enddo
```

B) Building  map_r
Function land_data.F90: set_land_state_ug() reads data for arrays grid_index and
ntiles_grid from file land_domain.nc. An unstructured domain is then built from
the SG and these arrays:

call mpp_define_unstruct_domain(lnd%ug_domain, lnd%sg_domain, num_land, ntiles_grid,
      mpp_npes(), npes_io_group, grid_index, name='LAND MODEL'

array grid_index is repurposed and set from the ug_domain:
```c
  !--- get the i,j index of each unstructured grid.
  allocate(grid_index(lnd%ls:lnd%le))
  call mpp_get_UG_domain_grid_index(lnd%ug_domain, grid_index)
  lnd%gs = grid_index(lnd%ls)
  lnd%ge = grid_index(lnd%le)
```

Finally, integer map_r(lat_i, lon_j) is set in land_model.F90::check_mask_map like this:
```c
do it = 1,size(idx)
     k = idx(it)
     if (k < 0) cycle
     g = modulo(k,lnd%nlon*lnd%nlat)+1
     if (g<lnd%gs.or.g>lnd%ge) cycle ! skip points outside of domain
     i = modulo(k,lnd%nlon)+1 ; k = k/lnd%nlon
     j = modulo(k,lnd%nlat)+1
     map_r(i,j) = 1
  enddo
```

**Comment by ngs333** [comment]
I tested some of the ideas above by forcing FMS to always use the great circle algorithm (to always use mosaic.F90::calc_mosaic_grid_great_circle_area() instead of calc_mosaic_grid_area() and the discrepancies between map_r and map_g remained the same.

**Comment by ngs333** [comment]
A note concerning lm4p test code directly reading indexes from land_domain.nc. Land_domain.nc is only in directory src_restart, which is not the directory I expected to be read by the lm4p code. However, that directories ```land.res.tile<i>.nc```  are equivalent to those with the same name in the other directories. Thy have the same non-zero land-sea boundary points. So I am back on the opinion that instead of map_r having too many points as non-zero, its probably map_g that does not have enough. So again I will look at the construction of the SG and the UG,

**Comment by ngs333** [comment]
Rs in these images show location of discrepancy. Faces 2,3,4 and 5 have similar discrepancies.
![rl_discrepancy_face1](https://user-images.githubusercontent.com/42479054/106052825-0dff0d80-60b8-11eb-874d-15a1ec4ce659.png)
![rl_discrepancy_face6](https://user-images.githubusercontent.com/42479054/106052826-0dff0d80-60b8-11eb-93a4-c17bbbef36c2.png)

**Comment by ngs333** [comment]
@nikizadehgfdl @jwdGFDL @bensonr 
The lm4p code that generates the two images above calculates a grid cell areas of zero for those grid points labeled R. Those are the discrepancies in the issue. I seems that because  the R's are not on the poles, this issue isn't related to #42 , #44 , #45. Is that correct?

**Comment by nikizadehgfdl** [comment]
I doubt it is related to those issues,  since those happen only when the grid cell touch or include a pole. 
I have not seen a grid cell area coming out zero, unless it is bypassed and not calculated at all (which  could happen if there is a logic error).
These points are all on the coast where any algorithm would have a hard time to decide between wet and dry. Doesn't that decision happen before area gets calculated?  Are  these  "exchange grid" area cells you are showing? How are they calculated?  Can you point us to the call?

**Comment by ngs333** [comment]
@nikizadehgfdl 
They are in an lm4p code that Sergey M instrumented.  Above I have a rough outline of it above that I wrote about a week ago.  See sections "Building map_g" and "Building map_r" above. Also, I can go over the code in a google meet is you want.

**Comment by ngs333** [comment]
Leaving the lm4p aside for a moment, I am looking for test that is essentially an "Indentity" remapping by the remap_land app such that it remapped the restart files to themselves. That would make it easier to check the correctness or lack thereof of remapped land, albeit in a simpler transform.

**Comment by ngs333** [comment]
I have just found that the shell script orchestrating the run of the remap_land app , once the remapping is  finished, is  overriding the src_restart directory with the contents of the dst_restart directory. I.e. it was overriding some of original input files with the created/output files (including the ```land_res_tile<X>.nc``` files).Consequently, the app I wrote to detect discrepancies would necessarily detect none in some of the relevant files.. 

 Looking anew at the data, there are differences between the files like ```dst_restart/and_res_tile1.nc``` and ```src_restart/land_res_tile1.nc```!  For example, for the "soil" field, the NW corner of Spain is missing (or has NC_FILL_INT)  in the src file, but its  present in the dst file (and actually in all other corresponding files). 

This above greatly narrows the  source of the discrepancy in question.  Probably the result should be zero  in agreement with array map_g (created by the  lm4p code from the grid spec) . The land app has this line (approximately line 1330 in one version) :

```land_frac_dst[ntile_dst * i + pos] = soil_frac_src[ntile_src * p + l] * soil_frac_cold[i]```

which means that when the soil field is zero in the src restart file, it should be zero in the remapped one.  
Somehow its yielding non-zeros.

**Comment by slm7826** [comment]
In my understanding the whole point is to make soil (and other) fractions in remapped restart to be consistent with dst cold start. So if the soil in non-zero in particular grid cell in dst, the soil information should come from the point in src where  the soil ruction is non-zero. This should be ensured by proper index in `soil_frac_src` array, in this case `ntile_src * p + l`.

**Comment by ngs333** [comment]
The source of the bug we are currently seeing is that function  full_search_nearest() is reporting the incorrect nearest neighbor
when identifying, for each point in the destination grid, the corresponding, or nearest point in the source grid.  For each of the thirty-nine discrepancies (according to lm4p code, the land points in the restart file that are not in the grid spec), function full_search_nearest find a point that is off by one index in either the i or the j direction. This is not the case for points that are OK.
For example, two known discrepancy points on face 1  are (48,94) and (68,94). Their index in the source grid are 9072 and 9092, respective.  In this C96 to C96 mapping, in the destination grid should also be be 9072 and 9092 respectively; instead, full_search_nearest() finds 9073 and 9093 
Printed out below by the function debug_display_points:
Errs: ii,jj: 48,94  ids_s=9072 face_map=0 idx_map=9073
Errs: ii,jj: 68,94  ids_s=9092 face_map=0 idx_map=9093
(BTW for land points  that do not have a discrepancy, it prints the indices to be matching, for example.
OKs: ii,jj: 4,14  ids_s=1348 face_map=0 idx_map=1348
OKs: ii,jj: 4,19  ids_s=1828 face_map=0 idx_map=1828
And for ocean points, it prints, for example:
OKs: ii,jj: 39,79  ids_s=7623 face_map=-1 idx_map=-1
OKs: ii,jj: 29,69  ids_s=6653 face_map=-1 idx_map=-1)

One of the indices being calculated is array idx_map_soil, which contributes to the variable ```p``` in the formula 
```land_frac_dst[ntile_dst * i + pos] = soil_frac_src[ntile_src * p + l] * soil_frac_cold[i]```

**Comment by ngs333** [comment]
It looks like I have to take a step backward and the issue is really not identified, though it is probably narrowed. From my previous analysis of February 2 and  3, I was tempted to resolve the discrepancy at the boundary points by changing either the function full_search_nearest() or the way its used so that in the end the product dst_grid/land.res.tile1.nc did not have on land the land-sea boundary grid points of issue.  However, after considering everything again, particularly Sergey’s comment on January 29 that “if the soil in non-zero in particular grid cell in dst, the soil information should come from the point in src where the soil fraction is non-zero”, I now conclude my plan was a bad idea.  i.e. the way full_search_nearest() currently works supports a result that is in agreement with Sergey's opinion.
Considering the state of the files (see table 1 below) , where file dst_restart/land.res.tile1.nc does have on land the boundary points at issue, and that it is correct because its is agreement with dst_grid/land_mask_tile1.nc, it is quite likely that the discrepancy error is in building the 2D domain from the grid spec. Some possibilities are:

a)  lm4p+ is not reading the right grid spec (dst_grid)
b) lm4p+FMS is not reading the dst grid spec correctly. This may be because there is an error in the dst grid spec that allows remap_land and other programs to read it one way but FMS to read it another way.
c) lm4p+FMS is not building the domain correctly from the grid spec.
d) And since the grid spec does not have the great circle algorithm label (https://github.com/NOAA-GFDL/FRE-NCtools/issues/36#issuecomment-762896396) 

Table 1. The value of the fields checked by custom program and  by ncview.
file | fields | Defined and positive field value, or (cell on land) | other
-- | -- | -- | --
dst_cold_start/lan.res.tile1.nc | frac, vegn | Y | A remap_land  input file
src_restart/land.res.tile1.nc | frac; vegn | N | A remap_land input file
dst_grid/land_mask_tile1.nc | mask | (Y) | A remap_land input file
dst_restart/land.res.tile1.nc | frac, vegn | Y | The remap_land output file. 			Field is positive because it is present in the dst_grid and 			full_search_nearest associates to it the nearest non-masked out in 			src_restart. Actual field cell values depend on the three files 			above.

**Comment by ngs333** [comment]
Sergey ( @slm7826  )  recently made some progress on the source of the discrepancy mentioned above.  He writes:
"I think the issue is the domain decomposition and, more precisely, inconsistency between the remapped restart and the land_domain file. With unstructured domains, a feature was introduced to balance the load on different processor by recording the number of sub-grid tiles per land grid cell, and using these numbers on the next run to distribute roughly the same number of tiles (as opposed to grid cells) per PE.

Naturally, when a restart is remapped, the number of tiles per grid cell no longer matches the numbers in land_domain file. Apparently in this case unstructured domain decomposition in the model gets confused, with some grid points silently skipped. I think that is what was causing the problem with grid match.

To avoid this issue, land_domain can be regenerated or simply removed

**Comment by ngs333** [comment]
Status 4/3/21.
4D cohort data was not being mapped correctly because the index was degenerate in the cohort dimension (It was of length 1).  The code was improved with a new way of creating the index and also of using it. This was tested by remapping  the sample data and the data appears to be remapped correctly.  The remapped data was also used in an lm4p experiment as the input restart data. The experiment seems to have completed successfully and Sergey Malyshev will perform additional inspection of the results.

**Comment by ngs333** [comment]
Status 3/11/2021
Sorry I have not figured the source of the errors of the cohort data remapping with the new index yet.
Right not I am investigating the possibility that the tile index is not being generated
correctly . The new (cohort related software) is built upon the older software that generates
the tile index; but it seems that there may be incorrect mapping of the tile index and therefore 
of the cohort data. For example, there is some cohort data at higher number tiles that is not copied
because the tile index itself is not present. (In fact, for cohort 0, the cohort incidences should be 
the same as the tile index; and in fact in both the src and dst  vegn().res.tile<n>.nc they are the same – barring what is filtered bu the cold start data).
