### ISSUE TITLE
make_coupler_mosaic breaks with --wave_mosaic flag after bronx-11

### ISSUE THREAD

**Issue by breichl** [NOAA-GFDL/FRE-NCtools#4]
**Describe the bug**
The make_coupler_mosaic program fails due to a memory error if run with the --wave_mosaic flag.  This issue appears in bronx-12 and subsequent releases, but is absent in bronx-11 and several prior versions.

**To Reproduce**

A simple idealized domain with the --wave_mosaic flag will reproduce the error.  The following set of commands is successful in bronx-11, but fails in more recent versions:

make_hgrid --grid_type regular_lonlat_grid --nxbnd 2 --nybnd 2 --xbnd 100,110 --ybnd 10,20 --nlon 20 --nlat 20 --grid_name ocean_hgrid
make_solo_mosaic --num_tiles 1 --dir ./ --mosaic_name ocean_mosaic --tile_file ocean_hgrid.nc --periodx 360 --periody 360
make_solo_mosaic --num_tiles 1 --dir ./ --mosaic_name atmos_mosaic --tile_file ocean_hgrid.nc --periodx 360 --periody 360
make_solo_mosaic --num_tiles 1 --dir ./ --mosaic_name land_mosaic --tile_file ocean_hgrid.nc --periodx 360 --periody 360
make_solo_mosaic --num_tiles 1 --dir ./ --mosaic_name wave_mosaic --tile_file ocean_hgrid.nc --periodx 360 --periody 360
make_topog --mosaic ocean_mosaic.nc --topog_type  rectangular_basin --bottom_depth 4000
make_coupler_mosaic --atmos_mosaic atmos_mosaic.nc --land_mosaic land_mosaic.nc --ocean_mosaic ocean_mosaic.nc --wave_mosaic wave_mosaic.nc --ocean_topog topog.nc --mosaic_name grid_spec

**Expected behavior**
The make_coupler_mosaic program fails with a segmentation fault.  On Gaea, with the --verbose --check flags, the error is slightly different depending on whether running with a different wave_mosaic.nc and ocean_mosaic.nc or supplying the same mosaic file for each.

With --wave_mosaic wave_mosaic.nc:
"Error in `make_coupler_mosaic': munmap_chunk(): invalid pointer: 0x000000"  when run 

With --wave_mosaic ocean_mosaic.nc:
"Error in `make_coupler_mosaic': free(): invalid pointer: 0x000000000b2ac900"

**System Environment**
The bug is found using default installations via module load fre/bronx-15 (or any release after 11) on both Gaea and the GFDL workstations.

**Comment by LuisSalbey** [comment]
Thanks a lot for reporting this problem. We had previously diagnosed the issue to a bug in C pointers, and was already fixed. The fix was included in Bronx-17 and later. 

Please re-open if the problem is not resolved using Bronx-18.
