### ISSUE TITLE
Need to add `echo "$output"` to test scripts

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FRE-NCtools#40]
**Describe the bug**
When the test scripts fail, and VERBOSE is set, only a cryptic message is printed indicating where the test script failed.  However, without the job's output it can be difficult if not impossible to determine the cause.  This is especially true when a job in the CI fails.  To resolve this, adding `echo "$output"` as the first command after the bats `run` command will cause the output to be dumped to the screen if the test fails.

**To Reproduce**
Run a failed test with `make VERBOSE=1 check`

**Expected behavior**
The output of the failed test should be outputted to the screen with `make VERBOSE=1 check`.

**System Environment**
All systems

**Comment by ceblanton** [comment]
With these updates the test failure details, either from make check with the VERBOSE=1 option or always in the `test-suite.log`, is improved.

The old message:
```
not ok 1 Test no stretched grid data lats 32.0 34.0 35.4
FAIL: Test32-fregrid_no_stretched.sh 1 Test no stretched grid data lats 32.0 34.0 35.4
# (in test file Test32-fregrid_no_stretched.sh, line 68) 
#   `expr ${var_32_0} \< 0' failed
# 9.97102e-07
# 0
ERROR: Test32-fregrid_no_stretched.sh - exited with status 1
```

compared to the new message:
```
not ok 1 Test no stretched grid data lats 32.0 34.0 35.4
FAIL: Test32-fregrid_no_stretched.sh 1 Test no stretched grid data lats 32.0 34.0 35.4
# (from function `run_and_check' in file test_utils.bash, line 90, 
#  in test file Test32-fregrid_no_stretched.sh, line 85) 
#   `run_and_check expr ${var_32_0} \< 0' failed
# 9.97102e-07
# failed: expr 0.000000997 < 0 
# 0
ERROR: Test32-fregrid_no_stretched.sh - exited with status 1
```
