### ISSUE TITLE
Add Copyright years

### ISSUE THREAD

**Issue by ngs333** [NOAA-GFDL/FRE-NCtools#46]
It may be beneficial to add the Copyright years to FRE-NCTools files.
Please see this thread from @underwoo https://github.com/NOAA-GFDL/FRE-NCtools/pull/43#discussion_r562761723.
Also see the discussions in this issue  https://github.com/NOAA-GFDL/FRE-NCtools/issues/24  and in this PR https://github.com/NOAA-GFDL/FRE-NCtools/pull/43

**Comment by underwoo** [comment]
@ngs333, as discussed this can be accomplished on a file-by-file basis as files are updated.  There is little need now to ensure all files have a copyright year.  As PRs come in, please verify the new files have a copyright year.
