### ISSUE TITLE
run.cr_simple_hydrog.csh fails and wipes the entire FTMPDIR

### ISSUE THREAD

**Issue by ngs333** [NOAA-GFDL/FRE-NCtools#47]
When I try to run run.cr_simple_hydrog.csh from a sub-directory of $FTMPDIR, it fails with the following messages:
an106: /vftmp/Sergey.Malyshev/pid20895/hydro > ./run.cr_simple_hydrog.csh 
ERROR: invalid platform
In addition, everything in the $FTMPDIR directory is wiped out by the script. This could potentially result in significant loss of work, if there are other directories in $FTMPDIR that are being used for, say, data accumulation or processing. The "invalid platform" error message appears to be spurious, caused by the fact that in my case the current working directory was also removed.
Ideally, a script should create its own unique temporary directory, if necessary.
@slm7826
@ngs333 This is gitlab issue #65

**Comment by ceblanton** [comment]
Hi @ngs333, @LuisSalbey and I modified the original `run.cr_simple_hydrog.csh`, and renamed it `make_simple_hydrog.csh` in the process. The script included in this repo is the `make_simple_hydrog.csh` currently.

**Comment by ceblanton** [comment]
However, we didn't fix that bad behavior you see, unfortunately. I agree it is suboptimal and even dangerous.

**Comment by ngs333** [comment]
@slm7826
Hi Sergey. Sorry we took so long to get to this issue. The original script ( run.cr_simple_hydrog.sh) was updated a while ago, and now renamed make_simple_hydrog.sh. The new script is in dir FRE-NCtools/tools/simple_hydrog;  and it seems the old script was somehow deprecated and yet kept and and put in dir FRE-NCtools/tools/simple_hydrog/old.

I agree its bad to wipe out the directory. It looks like both scripts do that, and the new one will be changed this week. Possibly to just make a new dir with mktemp and to work from there.

I am wondering if you are still using, want to use, or know someone that is using the old script.
Thanks
Mike Z

**Comment by slm7826** [comment]
Hi Miguel,

I have not used this script since the time I submitted the ticket; I am not sure if anyone is using the old version. 

Not that it would help you very much, but I think the most likely people to use this script (old or new) are the ones who create new grid specs and want to run something quick without going through manual creation of the hydrography. Not sure how to identify them though.

--
Sergey

**Comment by ngs333** [comment]
@slm7826 
Sergey,
Thanks for the input.
MZ
