### ISSUE TITLE
Assemble available documentation

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#5]
**Is your question related to a problem? Please describe.**
This collection of tools, FRE-NCtools, has developed over the years to support GFDL's FRE workflow. The tools have command-line usage help, but documentation detail and quality varies after that.

Please collect and organize all available documentation on the FRE-ncotols within this repository.

**Comment by LuisSalbey** [comment]
[specific_tools_description_hydrology_script.docx](https://github.com/NOAA-GFDL/FRE-NCtools/files/5164315/specific_tools_description_hydrology_script.docx)

**Comment by ceblanton** [comment]
Yes, documentation- but this too vague to be useful
