### ISSUE TITLE
fregrid bilinear interpolation gives different lat bounds than expected

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#50]
**Describe the bug**
When specifying the non-global output grid with fregrid (using the --latBegin, --latEnd, --lonBegin, --lonEnd options), the output grid is different depending on the interpolation method. In particular, the bilinear option gives a different output grid than the others.

**To Reproduce**
Use fregrid as usual to regrid a grid to a non-global output, using the --(lat|lon)(End|Begin) options. Use the regular option first (conserve_order1), then try bilinear.

**Expected behavior**
The output grid should be the same regardless of interpolation option.

**System Environment**
Any

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by spencerkclark** [comment]
Thanks for posting this issue @ceblanton -- this confused me initially as well.

**Comment by spencerkclark** [comment]
Oops I actually misread the issue slightly, but it is likely related.  My experience was using global data (I guess one can think of global as a special case of regional).  In the global case by default using the bilinear option resulted in grid cell centers that included the poles (i.e. latitudes -90 and 90), whereas using the conservative options led to grid cell centers that did not include the poles (i.e. when regridding to a 1-degree grid, -89.5 and 89.5).  The solution was to set `--latBegin -89.5` and `--latEnd 89.5` in my call.  It seems like bilinear defaults to interpolating to grid cell centers that are on the edges of the domain, while conservative defaults to interpolating to grid cells that completely fit within the bounds of the domain.

I guess one thing that comes to mind before changing this behavior is that if one liked the bilinear behavior from before--I know some reanalysis datasets include data at the poles--I'm not sure how one would easily get it back.  At least there is an easy workaround for my use-case.

**Comment by ceblanton** [comment]
Thank you @spencerkclark for the additional details, and sorry for the long pause.

To repeat/sum up the discrepancy, the `conserve_order1` and `conserve_order2` regridding methods interpret the lat and lon limits provided by the user (via --latBegin, --latEnd, --lonBegin, --lonEnd) as the **edges** of the desired output domain, so that the `lat_bnds` and `lon_bnds` reflect the area of interest. For the global output domain, the `lat_bnds` and `lon_bnds` are 0 and 90, and 0 and 360. (99+% of fregrid calls use these one of these two regridding methods).

When using the `bilinear` regridding method, the *longitude* is interpreted identically, so that the user requested range (--lonBegin, --lonEnd) is the longitude edges. However, the *latitude* is interpreted differently: the user requested range (--latBegin, --latEnd) is the **cell center** of the output domain. The `lat_bnds` then exceeds the range requested by the user. For the global output domain, `lat` is 0 and 90, with the `lat_bnds` being half a grid point less and greater. (Having latitude bounds less than 0 and greater than 90 is unrealistic, isn't it?)

In my (slight) opinion, the `bilinear` anomaly related to the latitude bounds is a bug that should be fixed. The behavior is inconsistent even within the bilinear option (longitude is interpreted on the cell edges, latitude on the cell center), as well as being inconsistent with the 1st and 2nd conserve schemes.

I do not believe anyone is taking advantage of this unusual bilinear bounds behavior to get the grid center on the poles, and in practice bilinear is rarely used.

What do you think? My slight opinion is that it makes sense to fix this, so that the lat/lon command-line behavior does not depend on interpolation method, which is inconsistent and surprising. Thanks for the feedback and thanks again for reporting this unusual fregrid behavior.

**Comment by spencerkclark** [comment]
Thanks -- I totally agree @ceblanton -- I was mostly playing devils advocate and trying to think about what the possible motivation for the existing behavior could have been.  I also lean towards harmonizing this with the other regridding methods.

ERA5 is the primary reanalysis dataset I am thinking of.  I know some folks on the @NOAA-GFDL/shield team compare to this dataset on occasion (tagging them in case any of them rely on this detail of the bilinear interpolation method in `fregrid` in any way).

**Comment by linjiongzhou** [comment]
I use NCL functions (ESMF_regrid or area_conserve_remap) to interpolate ERA5 data.

**Comment by spencerkclark** [comment]
Thanks @linjiongzhou -- that's good to know that you would not be affected by this.

**Comment by ngs333** [comment]
@spencerkclark @ceblanton 
There is a fregrid option that is related to this:
 ```
  " --center_y               output latitude will locate at cell center, i.e., the   ",
  "                              starting latitude will be -89 when nlat = 90. when      ",
  "                              center_y is not set, starting latitude will be -90. for ",
  "                              bilinear interpolation. For conservative interpolation, ",
  "                              center_y is assumed.   "
```

**Comment by ceblanton** [comment]
@ngs333 Great find- you're completely right! I'm embarrassed I didn't notice that option sitting there the whole time. Using --center_y with bilinear interpolation produces the same grid as conservative. (As the documentation there states...)

In our opinion, the default would be better as reversed, so that --center_y is set by default, with a --no-center-y option to produce grids with the grid centers on the poles.

But since the scenario is already documented in the usage notes, I think we can probably close this issue.

**Comment by spencerkclark** [comment]
Indeed thanks @ngs333!  It's nice that this is already built in.  I am fine with closing this issue as well.

**Comment by lharris4** [comment]
Hi, all. Glad we could find this little nugget within FREgrid.

Thanks,
Lucas

**Comment by ceblanton** [comment]
While fregrid bilinear interpolation gives different lat bounds than conservative interpolation by default, adding the `--center_y` option produces the same lat bounds.
