### ISSUE TITLE
Reduce repository size

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#51]
**Is your feature request related to a problem? Please describe.**
At 1.6 GB currently, this repo is a bit unwieldy to clone.

**Describe the solution you'd like**
Keep the test files somewhere else (ftp server or git-lfs) so that the repo is much smaller.

**Describe alternatives you've considered**

**Additional context**

**Comment by ngs333** [comment]
This issue( https://github.com/NOAA-GFDL/FRE-NCtools/issues/76 )Possibly both should behandled together.

**Comment by ceblanton** [comment]
duplicate of #76
