### ISSUE TITLE
New tool to regrid between two different atmos hybrid coordinate grids

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#56]
**Is your feature request related to a problem? Please describe.**
`plevel.sh` regrids from hybrid vertical coordinate to standard pressure levels. A user has requested a similar tool to regrid to a different hybrid coordinate grid. The proposed use case would be to compare output from reanalysis datasets on an identical vertical grid.

**Describe the solution you'd like**
Tool would accept as inputs:
- Input file, on a hybrid atmos grid. Containing variables to regrid (e.g. ua) and hybrid coordinate specification (ps, pk, bk)
- Requested output hybrid grid parameters (ps2, pk2, bk2). This would take the form of a second input file
- Requested variables to regrid

Tool would output:
- output file, containing requested variables to regrid on the specified output grid

**Describe alternatives you've considered**

**Additional context**
vertical pressure P = pk + bk * ps

**Comment by underwoo** [comment]
There are too many ways to do this, and not all will agree with any given method.  We have not induced vertical interpolation for that reason.  Users can generate their own tools for vertical interpolation as they need.
