### ISSUE TITLE
Make and Make Install running into errors

### ISSUE THREAD

**Issue by mborrus** [NOAA-GFDL/FRE-NCtools#62]
**Background**
I have data from an AM4 run and want to regrid the six .nc files from cubed-sphere to a lat-lon grid. 
The data is stored on an HPC in a folder I can write to. The HPC has netCDF and other key modules already installed. The only thing I'm missing is this package/repo, FRE-NCtools, but I'm having trouble installing it. 
The documentation suggests that I have the permissions to do, so I believe as long as I install it to a home folder, I shouldn't run into issues with needing root privileges ([documentation](https://www.sherlock.stanford.edu/docs/software/overview/)).

**What I've have tried**
1. I forked the repo and created a new <site> folder in /FRE-NCtools/site-configs/ to match the conventions of the HPC. The files are viewable here ([My Site Folder](https://github.com/mborrus/FRE-NCtools/tree/master/site-configs/stan)). I may have over-added modules because I couldn't find nccmp in the list available. I had trouble finding much information about it online (not sure what the abbreviation is...). It ran further when I got rid of the config.site file, hence why there isn't one. 
2. I cloned the fork into my home folder (/home/users/<username>)
`git clone <my_url>` 
3. I moved into the new directory `cd ./FRE-NCtools/`
4. Set the environment variable CONFIG_SITE and set the recommended environment
`export CONFIG_SITE=/home/users/mborrus/FRE-NCtools/site-configs/stan/config.site
 source /home/users/mborrus/FRE-NCtools/site-configs/stan/env.sh`
5. `autoreconf -i`
6. `./configure --prefix=/home/users/mborrus`
7.  `make`
Errors incoming! It's long, [so I copied and pasted it here](https://github.com/mborrus/FRE-NCtools/blob/master/Make_Error_Output). 
8. I tried pressing on, not knowing if these were fatal errors, so I tried a `make install`
More errors! T[hese are linked here. ](https://github.com/mborrus/FRE-NCtools/blob/master/Make_Install_Errors).

I can't quite decipher what's going wrong here, or what may be causing it. Is it due to my lack of config.site file? 

What's a good way to check if the install is successful? 

Thanks for any help and let me know if I'm forgetting anything...

**Comment by ngs333** [comment]
@mborrus 
I am not sure your environment is correct. First, there is an alternative to your step 4 at this link:
 https://github.com/NOAA-GFDL/FRE-NCtools/issues/35#issuecomment-751040087
Can you set up your compilation env flags that way?

Also,
I believe older version of gcc might encounter the compilation problems you see. Can you let me know the version of gcc yhat you are using? Thanks

**Comment by mborrus** [comment]
I'll look more into the alternative comment you linked now. 

To quickly respond to your second point: GCC is loaded with 6.3.0 as the default. If I try to load ICC, which the .env files do, I get a message: 

`Lmod is automatically replacing "gcc/6.3.0" with "icc/2019"`

If I then load GCC, I get a message:

`Lmod is automatically replacing "icc/2019" with "gcc/6.3.0".`

Not sure how to remedy this.

**Comment by mborrus** [comment]
Following your comment, I was able to get a bin folder with some of the commands, but it looks like the `make` gets stalled out about half way, so I don't get any of the grid tools... sadly those are the ones I need. 

When I did make with GCC, I get a fatal error saying the netcdf.mod is made with a different version of Fortran:
`Fatal Error: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.
make[2]: *** [nc_null_check.o] Error 1
make[2]: Leaving directory `/home/users/mborrus/FRE-NCtools/build/tools/nc_null_check'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/users/mborrus/FRE-NCtools/build'`

When I do it with ICC, it stalls out half way and I can build it, but once again, only half the tools.

We made a change to the makefile -
NETCDFF_VERSION = netCDF-Fortran 4.4.1.1 
was originally
NETCDFF_VERSION = netCDF-Fortran 4.4.4.4
Then we did `make` with gcc, got the above error, tried `make` again with icc, and it ran through.

Complicated path, but all the tools are in the folder now. I guess that's it!

**Comment by ngs333** [comment]
@mborrus The netcdf and the compiler have to be compatible.  
If you (module) load one of them, you normally have to also  load the other.  In the systems I work with,
If one load the compiler and the netcdf, and then loads a different compiler, the system automatically warns that is is
also switching netcdf libs. It looks like in your system you are going to have to manually take care of the compatibility.
 Once you have the compiler and netcdf squares, and their corresponding flags, you wont have to edit the Makefile - the Makefile that the autotools configure app generates will be correct.   IF you tried the script that I linked to but need a version for Intel compilers instead, let me know and I'll make one for you.

**Comment by mborrus** [comment]
@ngs333 As far as I know right now, the last script you linked to ended up working out. Thanks for your help!
