### ISSUE TITLE
make_hgrid segfaults in Test04-grid_coupled_nest.sh (on GFDL and GFDL-WS sites)

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#67]
**Describe the bug**
make_hgrid segfaults when using particular options and compiled on GFDL or GFDL-ws. This may be a recent problem, possibly since #63 

**To Reproduce**
Compile as usual on GFDL or GFDL-WS. Run Test04, or run the failing test directly which is:
```
# Create C144 grid for land
make_hgrid 
 --grid_type gnomonic_ed 
 --nlon 288 
 --grid_name land_grid 
 --do_schmidt 
 --target_lat 48.15 
 --target_lon -100.15 
 --halo 3 
 --stretch_factor 3 
 --great_circle_algorithm 
 --nest_grid 
 --refine_ratio 3 
 --parent_tile 0
```

**Expected behavior**
Pass the tests.

**System Environment**
GFDL and GFDL-ws as set in their env.sh files

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by ngs333** [comment]
@ceblanton 
Chris, I finally got to running make_hgrid in Intel Inspector and it does not look good. In fact, inspector indicates:
9 new problem(s) found 
    10 Incorrect memcpy call problem(s) detected 
    22 Invalid memory access problem(s) detected 
    26 Memory leak problem(s) detected 
    1 Memory not deallocated problem(s) detected 

We should fix any of the "memory leak" and "memory not deallocated" problems , yet even with these problems the code will run. However, those  "Invalid memory access" are likely real sources of wrong awnsers and/or core dumps / crashing. I bet some of these may be array out bounds kinds of errors - e.g. index into array miscalculated or misused.  So I am going to have to compile differently and or run in the debugger.

In the mean time, since this is likely a multi-day path, can you a) look at your program input arguments and make sure they are really legal, and b) re-run making sure you can capture core dumps. You may have to set the ulimit = unlimited . That way we might be able to narrow down the problem faster. Thanks

**Comment by ceblanton** [comment]
Interesting, that looks ominous indeed. Here is a core dump running the test case

`make_hgrid --grid_type gnomonic_ed --nlon 288 --grid_name land_grid --do_schmidt --target_lat 48.15 --target_lon -100.15 --halo 3 --stretch_factor 3 --great_circle_algorithm --nest_grid --refine_ratio 3 --parent_tile 0`

`/net2/Chris.Blanton/fre-nctools-make_hgrid-segfault/core.54173`

Will I need to recompile with debug symbols for it to be useful?

**Comment by ceblanton** [comment]
```
(gdb) where
#0  create_gnomonic_cubic_grid (grid_type=0x2b095f169118 "", nlon=0x0, nlat=0xae40620, x=0x225fee0 <sBuffer+28410752>, y=0x1, 
    dx=0x225fef, dy=0x2b095ac9f010, area=0x2b09567d5010, angle_dx=0x2b095cf09010, angle_dy=0x2b095f169010, 
    shift_fac=-60.157299726803949, do_schmidt=1, do_cube_transform=0, stretch_factor=1.0477780150574778, 
    target_lon=4.6869551004748276e-06, target_lat=0.0021649376666488251, num_nest_grids=1, parent_tile=0x7ffe7242bd50, 
    refine_ratio=0x7ffe7242bf50, istart_nest=0x7ffe7242b550, iend_nest=0x7ffe7242b750, jstart_nest=0x7ffe7242b950, 
    jend_nest=0x7ffe7242bb50, halo=3, output_length_angle=1) at create_gnomonic_cubic_grid.c:674
#1  0x000000000042ff4e in main (argc=1916979720, argv=0x7ffe7242c768) at make_hgrid.c:1097

**Comment by ngs333** [comment]
There is at least one logic bug in create_hgrid  that shows up with the input above. On lines 974 and 975, arrays nxl[] and nyl[] are created/allocated with array length of 6.  In the future they should be indexed with index i in [0,5]. In lines 1046 though 1050, their index is 6. This error is also an invalid memory access - an error that does not always result in the same output and side effects.

**Comment by ngs333** [comment]
@ceblanton 
It says in the make_hgrid documentation that the argument nest_grid is obsolete. Should we be testing with it?

**Comment by ceblanton** [comment]
@ngs333 I agree, the --nest_grid option should be updated to use --nest_grids=2. That is exactly equivalent, correct? (In the test case above it is equivalent, but I don't know about all uses).

**Comment by ngs333** [comment]
@ceblanton It appears that when a parent_tile of 0 is specified, the arrays nxl[] and nxy[] arent allocated to be large enough.
If parent_tile is in [1,6] , those arrays get an extra space.  I am trying to figure out want a parent_tile of zero means. Is it even legal?

**Comment by ngs333** [comment]
@ceblanton 
Can you please test with branch make_hgrid_core on my repo:

https://github.com/ngs333/FRE-NCtools/tree/make_hgrid_core

**Comment by ceblanton** [comment]
Thanks @ngs333- unfortunately, the seg fault problem appears to be unchanged

**Comment by ngs333** [comment]
I only removed the first occurring invalid memory access (IMA) problem, hoping that the others were cascading from that one. According to Intel Inspector, there were IMAs in create_gnomic_grid lines 252 - 255,  661 - 663,  673-674, 1643, 1644, 1654, 1655. So I have to fix some more.

**Comment by ngs333** [comment]
@ceblanton 
Although the first problem that occurs (in make_hgrid.c) did not cascade to be the cause of the remaining problems,
the first problem of the remaining problems (lines 252-255 in create_gnomonic_cubic_grid.c) are of the same kind.
For the case where parent_tile[0] == 0, a tile number array is two short to be accessed the way it is. I.e. it is the same logic error , although in a different file.

**Comment by ngs333** [comment]
@ceblanton 
I am trying to create a set of arguments that are equivalent to your original set but without using the obsolete singular "--nest_grid". For example, this set below ( which I need to verify with more knowledgeable people) sould be equivalent :
```./make_hgrid  --grid_type gnomonic_ed --nlon 288 --grid_name land_grid --do_schmidt --target_lat 48.15 --target_lon -100.15 --halo 3 --stretch_factor 3 --great_circle_algorithm --nest_grids 1 --refine_ratio 3 --parent_tile 1 --istart_nest 41 --jstart_nest 21 --iend_nest 200 --jend_nest 200 --halo 3```
However, even with these arguments, although the code completes execution, there is an invalid memory access (lines 673/674 in create_gnomonic_cubic_grid.c).  This is better than before but still I have to investigate some more.

**Comment by ceblanton** [comment]
@ngs333 It looks like perhaps the problem is the the original test case using singular `--nest_grid`. I'm also confused what the `--parent_tile 0` does since there is no tile 0, and that usage is missing the --istart_nest/... region specification. I agree that we should change this test to use the plural `--nest_grids`, which get past the seg fault at least (but still has memory access issues, I see).

I suggest we consider removing the `--nest_grid` option altogether if we can understand the usage enough to rephrase it in the `--nest_grids` form.

**Comment by ngs333** [comment]
The bug in the code is the first of these lines (approximately lines 670ff)  in file create_gnomonic_cubic_grid.c
``` 
     for(i=0; i<=(nx_nest_arr[nn]+1)*(ny_nest_arr[nn]+1); i++) {
        angle_dx[tile_offset_supergrid[ntiles+nn] + i]=0;
        angle_dy[tile_offset_supergrid[ntiles+nn] + i]=0;
      }```

The ''<=" should b changed to ```<```. If left as is, there is one write outside the bounds of arrays angle_dx[] and angle_dy[].
In principle, the memory being overwritten can be almost any memory; exactly what memory is overwritten can be compiler and build dependent. It can affect answers or possibly cause core dumps.

**Comment by ceblanton** [comment]
Hi @ngs333 I think there is another memory leak out there, unfortunately. This fix (https://github.com/ngs333/FRE-NCtools/tree/make_hgrid_abounds) still has the seg fault problem with the global refinement use case (--nest_grids 1 --parent_tile 0)

**Comment by ngs333** [comment]
@ceblanton  There is no parent tile 0  that it makes sense to use. This is part of the discussion I want to go over.

**Comment by ngs333** [comment]
@ceblanton 
I have update the code at (https://github.com/ngs333/FRE-NCtools/tree/make_hgrid_abounds) with fixes to several array out of bounds reads and memory leaks.
