### ISSUE TITLE
Set the run-time search path to include required libraries

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FRE-NCtools#87]
**Is your feature request related to a problem? Please describe.**
Traditionally, executables build for GFDL have set the rpath (run-time search path) to include required libraries. With this build setting, users can run the executables without having to set $LD_LIBRARY_PATH. During some updates to the build settings, this was lost from the build scripts.

**Describe the solution you'd like**
The best solution would be to set the rpath using native Autotools methods. @underwoo believes the following might do the trick:

"Modify the m4/ax_lib_netcdf.m4 macro to add `-Wl,-rpath -Wl,/path/to/netcdf` to the NETCDF_LDFLAGS and NETCDF_FCLDFLAGS variables.  These can then be added to AM_LDFLAGS in the `Makefile.am`s."

A shorter-term solution would be to set the LD_RUN_PATH environment variable within the site env.sh files:

setenv LD_RUN_PATH "`nc-config --libdir`:`nf-config --prefix`/lib"

This has the disadvantage of requiring users to remember to set this if they aren't using the env.sh scripts and maintaining this in the env.sh files. Also, it won't quite work, as the `nc-config` program isn't in the PATH until the env.sh script is `eval'd`. This is roughly equivalent:

setenv LD_RUN_PATH \$LD_LIBRARY_PATH

**Describe alternatives you've considered**

**Additional context**

**Comment by ceblanton** [comment]
After switching to GCC, we found that setting `LD_RUN_PATH` did not make the linker add the directory paths to the executable as the Intel compiler does. So this should be done for the 2022.01 release so that the executables can be run without module loading.

**Comment by ngs333** [comment]
@ceblanton , @underwoo , @bensonr 
Rusty reminded me yesterday that we can also copy the technique or code used for the ncview library. That is, in the configure.ac,
add these lines
```
if test x$ac_compiler_gnu = xyes; then
	RPATH_FLAGS=""
	for word in $NETCDF_LDFLAGS; do
		if test `expr $word : -L/` -eq 3; then
			#RPDIR=`expr substr $word 3 999`;
			RPDIR=${word:2}
			RPATH_FLAGS="$RPATH_FLAGS -Wl,-rpath,$RPDIR"
		fi
	done
	AC_SUBST(RPATH_FLAGS)
fi
```
and in the Makefile.am (of the code to be compile) add the  $RPATH_FLAGS to the LDADD var.

This worked for both .c and .F90 executables. I.e. After building, then doing a module purge, the build executables  can be run.

Also, on analysis, and with the code built with the cononical way, readelf and  ldd output seems to be as
expected:
```
readelf -d tools/make_hgrid/make_hgrid
readelf -d tools/make_hgrid/make_hgrid | grep RPA
 0x000000000000000f (RPATH)              Library rpath: [/app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/gcc/11.2.0-sp3zc57qx7ssulclz45mjwbybaoca42v/lib64:/app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/netcdf-c/4.8.1-kd2fizpbah22hkghjxhhzkwh2ekxetdj/lib]

ldd  tools/make_hgrid/make_hgrid
	linux-vdso.so.1 =>  (0x00007fff0a9d9000)
	libnetcdf.so.19 => /app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/netcdf-c/4.8.1-kd2fizpbah22hkghjxhhzkwh2ekxetdj/lib/libnetcdf.so.19 (0x00002ad78b954000)
	libm.so.6 => /lib64/libm.so.6 (0x00002ad78bd10000)
	libc.so.6 => /lib64/libc.so.6 (0x00002ad78c012000)
	libhdf5_hl.so.100 => /app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/hdf5/1.10.7-sscvozf7ndffhvzfvzxogjc2gwelc2zl/lib/libhdf5_hl.so.100 (0x00002ad78c3e0000)
	libhdf5.so.103 => /app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/hdf5/1.10.7-sscvozf7ndffhvzfvzxogjc2gwelc2zl/lib/libhdf5.so.103 (0x00002ad78c602000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002ad78cbc1000)
	libz.so.1 => /app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/zlib/1.2.11-txwhoi6xu6mv4j7uykzah2bxh443opdk/lib/libz.so.1 (0x00002ad78cdc5000)
	libcurl.so.4 => /app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/curl/7.79.0-2qkizvn4kq2a2644snjxrrvasmmukrkb/lib/libcurl.so.4 (0x00002ad78cfdc000)
	libmpi.so.12 => /app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/mpich/3.4.2-ajx5aead2h3q362qvvv6pdjgciwwi22e/lib/libmpi.so.12 (0x00002ad78d26c000)
	/lib64/ld-linux-x86-64.so.2 (0x00002ad78b730000)
	libsz.so.2 => /app/spack/v0.17/linux-rhel7-x86_64/gcc-11.2.0/libaec/1.0.5-yjcojplf3rvpfr5xmwfkvkvyb4smso4s/lib64/libsz.so.2 (0x00002ad78e05f000)
```
Next week I will try again to code the technique modifying  NETCDF_LDFLAGS and NETCDF_FCLDFLAGS ( suggested above 
https://github.com/NOAA-GFDL/FRE-NCtools/issues/87#issue-887864554 )
