### ISSUE TITLE
Switch GFDL site configurations to GCC

### ISSUE THREAD

**Issue by ngs333** [NOAA-GFDL/FRE-NCtools#99]
NCTools needs to document and set GCC compiler flags and settings for use after the 18.1 release.
A good set of flags will consider the parameters of reproducible with Bronx-18, speed of execution, and help in debugging working executables, and help in adding and maintaining code.

Both the config.site files and documentation may need changes.

**Comment by ceblanton** [comment]
Currently, GCC 9.2.0 works OK on workstations and 10.3.0 works OK on gaea with minimal site changes. But there is no suitable GCC on PAN currently.

https://github.com/ceblanton/FRE-NCtools/tree/99.gcc
